[context.production.environment]
  HUGO_VERSION = "0.118.2"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.118.2"

[build]
  command = "hugo"
  publish = "public"

[[redirects]]
  from = "/air-conditioners/"
  to = "/products/"

[[redirects]]
  from = "/furnaces/"
  to = "/products/"

[[redirects]]
  from = "/heat-pumps/"
  to = "/products/"

[[redirects]]
  from = "/indoor-air-quality/"
  to = "/products/"

[[redirects]]
  from = "/thermostats/"
  to = "/products/"

[[redirects]]
  from = "/boilers/"
  to = "/products/"

[[redirects]]
  from = "/geothermal/"
  to = "/products/"

[[redirects]]
  from = "/fireplaces/"
  to = "/services/"

[[redirects]]
  from = "/payments/"
  to = "/"